os:
  - linux

language:
  - python

python:
  - 2.7

install:
  - pip install -r dev-requirements.txt
  - python setup.py install

script:
 - coverage run --source {{cookiecutter.app_name}} -m py.test

after_success:
  - coveralls